"""Add users table

Revision ID: 488a202c88f4
Revises:
Create Date: 2025-09-28 19:26:07.983856

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "488a202c88f4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
