"""Add users table

Revision ID: 6c00a68f7817
Revises: 488a202c88f4
Create Date: 2025-09-28 19:27:00.307989

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "6c00a68f7817"
down_revision: Union[str, Sequence[str], None] = "488a202c88f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
