"""add uuid to users table

Revision ID: 588950002226
Revises: cf338982428b
Create Date: 2025-10-04 09:49:12.202277

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "588950002226"
down_revision: Union[str, Sequence[str], None] = "37973af9fab2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add UUID column to users table with default values
    op.add_column("users", sa.Column("uuid", sa.Uuid(), nullable=True))
    
    # Generate UUIDs for existing users
    op.execute("UPDATE users SET uuid = gen_random_uuid() WHERE uuid IS NULL")
    
    # Make UUID column non-nullable and add unique constraint
    op.alter_column("users", "uuid", nullable=False)
    op.create_unique_constraint(op.f("uq_users_uuid"), "users", ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_uuid"), "users", type_="unique")
    op.drop_column("users", "uuid")
    # ### end Alembic commands ###
